localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/ar.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/da.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/de.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/el.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/es.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/fil.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/fr.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/it.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/ja.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/ko.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/kk.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/nl.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/pl.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/pt-BR.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/ru.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/sv.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/th.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/tr.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/uk.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/ur.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/vi.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/zh-CN.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/zh-Hans.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/zh-HK.lproj/Localizable.strings -r
localisort -t ./Application/X/en.lproj/Localizable.strings -i ./Application/X/zh-TW.lproj/Localizable.strings -r
